### ISSUE TITLE
md5 checksum fails

### ISSUE THREAD

**Issue by apitanga** [officel/ansible-role-timezone#1]
A recent change/deprecation in Ansible breaks this playbook.

See https://github.com/ansible/ansible/issues/39095

This is the line that breaks: https://github.com/officel/ansible-role-timezone/blob/d729099ab9b826b48c37975d179754ecc3be9ff5/tasks/setup-centos6.yml#L9

**Comment by officel** [comment]
thank you for your PR #2 
maybe ok?

**Comment by apitanga** [comment]
I had to correct the syntax and add get_md5 to another line as well.  Sent another PR.  Tests successfully on RHEL7.6 now. Thanks for your attention

**Comment by officel** [comment]
Thank you good PR!!
I was thinking how to fix it...
Thank you again!!

**Comment by officel** [comment]
#2 
#3
