### ISSUE TITLE
Timezone as a variable

### ISSUE THREAD

**Issue by bbaassssiiee** [officel/ansible-role-timezone#4]
Consider making this role reusable by introducing a default variable for the timezone.

**Comment by officel** [comment]
Thank you for Issue.
I haven't used it for a while, so I can't deal with it right away, but I'll try to replace it by creating a default_zonename variable.

**Comment by officel** [comment]
maybe like this?
#5

**Comment by officel** [comment]
@bbaassssiiee Thank you for review.
